# S02 T04: Pràctica amb programació numèrica

### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [ ]:
import numpy as np
def resumArray(a):
    print("Suma de los números del array",a.sum())
    print("Número más pequeño del array",a.min())
    print("Número más grande del array",a.max(axis=0) )
    print("Media",a.mean() )
    print("Desviación estandar",np.std(a))

x = input("Escribe un array de números: ")
b = x.split()
res = [int(i) for i in b]
c = np.array(res)
resumArray(c)


### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [5]:
def randomMatrix(x):
    a = np.random.randint(100, size=(x,x))
    print(a)

x = input("Escribe el tamaño de la matriz: ")
b = int(x)
randomMatrix(b)

Escribe el tamaño de la matriz: 6
[[93 94 62 39 94 17]
 [57 59 79 28 56  9]
 [81  2 44 48 85 64]
 [20 21 28 97 87 63]
 [40  2 76 69 49 75]
 [13 93 42 93  0 85]]


### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [ ]:
x = input("Escribe el tamaño de la matriz: ")
b = int(x)
randomMatrix(b)

for i in range(0, b):
    for j in range(0, b):
    

### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.